cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.01.20/cdo.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.01.20/def.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.01.20/protovis.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.01.20/pvc.js
=> [CDF-459] - Update CCC version in CGG and Analyzer for BA Server 5.3

cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0/tipsy.js
=> [CDF-482] - CCC - Tipsy - Log level no longer synchronized with that of CCC

build.properties, build.xml
=> ENGOPS-640

cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/cdo.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/def.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/main.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/protovis-compat.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/protovis-standalone.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/protovis.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/pvc.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-15.05.07-dev/tipsy.js
=> [CDF-543] - Update CCC version in CGG and Analyzer for BA Server 5.4

cgg-core/ivy.xml, cgg-core/src/pt/webdetails/cgg/SVGChart.java, cgg-core/src/pt/webdetails/cgg/scripts/DefaultScriptResourceLoader.java, cgg-core/src/pt/webdetails/cgg/scripts/SystemScriptResourceLoader.java, cgg-core/test-src/pt/webdetails/cgg/CggGoldTestBase.java, cgg-pentaho-base/src/pt/webdetails/cgg/charts/SVGChart.java, cgg-pentaho5/src/pt/webdetails/cgg/CggService.java, cgg-pentaho5/src/pt/webdetails/cgg/scripts/JCRScriptResourceLoader.java, cgg-pentaho5/src/pt/webdetails/cgg/scripts/SystemFolderScriptResourceLoader.java
- fixed character encoding issues, default to UTF-8 (via CPF's CharsetHelper)
- added CPF dependency, for consistent CharsetHelper usage across plugins
=> [CDF-448, CDE-565]

build.xml
@diogofscmariano please review
=> [FIX] - Updated build.xml to correct building failure

cgg-pentaho5/ivy.xml
Changed "cpf-pentaho5" dependency to "cpf-pentaho"
@smaring @lgrill-pentaho
=> [CLEANUP] Updating cpf version

cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/cdo.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/def.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/main.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/protovis-compat.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/protovis-standalone.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/protovis.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/pvc.js, cgg-core/src/pt/webdetails/cgg/resources/ccc/2.0-6.1/tipsy.js
=> [CDF-874] - Update CCC version in CGG and Analyzer for BA Server 6.1

cgg-pentaho5/build.properties, cgg-pentaho5/ivy.xml
=> [CLEANUP] - correcting mondrian version

cgg-core/test-gold/gold/sample1/cccStub-svg-test.svg
=> [CLEANUP] Fix CGG Golden tests

cgg-core/test-gold/gold/sample1/cccRaw-svg-test.svg
=> [CLEANUP] Fix CGG Golden test ii

cgg-core/ivy.xml, cgg-core/src/pt/webdetails/cgg/resources/ccc/main.js, cgg-core/src/pt/webdetails/cgg/resources/cgg/dom.js, cgg-core/src/pt/webdetails/cgg/resources/define.js, cgg-core/src/pt/webdetails/cgg/scripts/AbstractScriptFactory.java, cgg-core/src/pt/webdetails/cgg/scripts/BaseScope.java, cgg-core/src/pt/webdetails/cgg/scripts/CompoundScriptResourceLoader.java, cgg-core/src/pt/webdetails/cgg/scripts/DefaultScriptResourceLoader.java, cgg-core/src/pt/webdetails/cgg/scripts/ScriptResourceLoader.java, cgg-core/src/pt/webdetails/cgg/scripts/SystemScriptResourceLoader.java, cgg-core/src/pt/webdetails/cgg/scripts/VirtualScriptResourceLoader.java, cgg-pentaho5/build.xml, cgg-pentaho5/ivy.xml, cgg-pentaho5/resources/plugin.xml, cgg-pentaho5/src/pt/webdetails/cgg/CggContentGenerator.java, cgg-pentaho5/src/pt/webdetails/cgg/CggService.java, cgg-pentaho5/src/pt/webdetails/cgg/WebCgg.java, cgg-pentaho5/src/pt/webdetails/cgg/scripts/JCRScriptFactory.java, cgg-pentaho5/src/pt/webdetails/cgg/scripts/JCRScriptResourceLoader.java, cgg-pentaho5/src/pt/webdetails/cgg/scripts/SystemFolderScriptResourceLoader.java, cgg-pentaho5/src/pt/webdetails/cgg/scripts/WebResourceLoader.java
Also, updated `define.js`
@pentaho/millenniumfalcon please review.
@nantunes, @davidmsantos90, @carlosrusso, @graimundo, @marcovala please review.
See related PRs at: https://github.com/pentaho/pentaho-analyzer/pull/1340.
=> [BACKLOG-7977] Adding support for loading web resource files.

cgg-core/test-gold/gold/sample1/cccRaw-svg-test.svg, cgg-core/test-gold/gold/sample1/cccStub-svg-test.svg
=> [BACKLOG-7977] Fixing golden tests.

cgg-reporting/ivy.xml
TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.
=> [BACKLOG-12334] GAV changes for reporting

cgg-pentaho5/src/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.ext.js
- Removed exception for BoxPlot
@dcleao please review
=> [BACKLOG-14077] 

cgg-pentaho5/src/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.ext.js
- Added new view types allowing its default property override matching cdf changes
@dcleao please review
=> [BACKLOG-14077]

cgg-core/ivy.xml, cgg-pentaho5/ivy.xml
=> [SP-3575][PPP-3737]-CGG: Use of vulnerable component Apache fop-0.94-CVE-2017-5661

cgg-core/ivy.xml, cgg-pentaho5/ivy.xml
=> [SP-3574][PPP-3737]-CGG: Use of vulnerable component Apache fop-0.94 -CVE-2017-5661

cgg-core/src/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.js, cgg-core/src/pt/webdetails/cgg/resources/define-cfg.js, cgg-pentaho5/src/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.ext.js
Depends on https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1157.
=> [BACKLOG-18432] Update due to VizAPI changes.

build-res/subfloor.xml, cgg-reporting/build-res/subfloor.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

cgg-core/build.properties, cgg-core/ivy.xml, cgg-pentaho/build.properties, cgg-pentaho/ivy.xml, cgg-pentaho5/build.properties, cgg-pentaho5/ivy.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

cgg-core/src/pt/webdetails/cgg/resources/define-cfg.js
=> [BACKLOG-19949] Update RequireJS config to match common-ui's.

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
Depends on: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1260
=> [BACKLOG-21825] Update RequireJS configuration.

core/src/main/java/pt/webdetails/cgg/SVGChart.java, core/src/main/java/pt/webdetails/cgg/output/PngOutputHandler.java, core/src/main/java/pt/webdetails/cgg/output/SVGOutputHandler.java, pentaho/src/main/java/pt/webdetails/cgg/CggService.java
=> [BACKLOG-22643] Fix SVG output to multipart body

core/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.js, core/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/SvgComponent.js, core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js, pentaho/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.ext.js
Now using common-ui's compressed bundle.
Merge with: https://github.com/pentaho/pentaho-analyzer/pull/1821.
=> [BACKLOG-23471] Refactor VizAPI module system. Update AMD configuration

core/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.js, core/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/SvgComponent.js, core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js, pentaho/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.ext.js
@webdetails/millenniumfalcon please *squash and merge*.
Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1302.
=> [BACKLOG-23466] Refactor VizAPI module system.

core/src/test/resources/test-gold/cgg/sample1/cccSupport/boilerplate.js
This is more to better diagnose the error.
=> [CLEANUP] Trying to fix intermittently failing test in CI.

core/src/test/resources/test-gold/cgg/sample1/cccSupport/boilerplate.js
=> [CLEANUP] Trying to fix intermittently failing test in CI (take 2).

core/src/main/java/pt/webdetails/cgg/scripts/BaseScope.java
=> [CLEANUP] Trying to fix intermittently failing test in CI (take 3).

core/src/test/resources/test-gold/gold/sample1/cccStub-svg-test.svg
@dcleao second pr for the other gold sample test
=> [TEST] - Fixing second test case for cgg

core/src/test/resources/test-gold/gold/sample1/cccRaw-svg-test.svg, core/src/test/resources/test-gold/gold/sample1/cccStub-svg-test.svg, core/src/test/resources/test-gold/gold/sample2/dial-svg-test.svg
Apparently, something has changed in the build environment.
At least, nothing relevant changed in the CCC source.
@jmcrfp, @webdetails/millenniumfalcon please review.
/cc @pamval
=> [CLEANUP] Small adjustments to Golden tests.

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js, pentaho/src/main/javascript/pt/webdetails/cgg/resources/cdf/components/ccc/BaseCccComponent.ext.js
=> [BACKLOG-27072] Rebalance View / Model: CGG

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
Depends on https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1394.
=> [BACKLOG-27093] Remove UIInfo.

core/src/main/javascript/pt/webdetails/cgg/resources/cdf-env.js, core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
@webdetails/millenniumfalcon please review
- Needs: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1397
=> [BACKLOG-27098] require config sync

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1399.
=> [BACKLOG-27098] Updating RequireJS configuration.

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
Merge along with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1409.
=> [BACKLOG-28658] Drilldown doesn't work in scatter visualization

js-intl-polyfill/pom.xml
=> [ANALYZER-3942] New POM lacks version

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
Must be merged together with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1577.
@himanshu6201, @varuntangirala, @NJtwentyone please review.
=> [BACKLOG-36156] Adding the new `pentaho/config/impl/Service` module to the `platformCore` RequireJS bundle

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
**PR set**: https://github.com/pentaho/pentaho-analyzer/pull/2288
@himanshu6201, @varuntangirala, @NJtwentyone, @rmansoor please review.
---
For reference, **original PRs** for the `analyzer-viz-view-config` branch where main code reviews were made:
- https://github.com/webdetails/cgg/pull/158
=> [BACKLOG-36156] PAZ visualization view configuration for 9.4

core/pom.xml
[PPP-4747] Vulnerable Component: batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4747] Vulnerable Component: batik-1.19

core/pom.xml, pom.xml
[PPP-4747] -Vulnerable Component :batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4747] -Vulnerable Component :batik-1.19

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
Repeating RequireJS changes affecting Waterfall ( as described in https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1707#discussion_r1379899250 )
=> [BACKLOG-38919] Added Waterfall Chart

core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
These changes were already reviewed and approved in #170
=> [BACKLOG-38691] - Create and Add Tree Map Visualization to the available list of Chart options in Analyzer
